version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-learning-backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=sqlite:///./app.db
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/app.db:/app/app.db
    restart: unless-stopped
    networks:
      - ai-learning-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-learning-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ai-learning-network

networks:
  ai-learning-network:
    driver: bridge
