apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: ai-learning-backend
spec:
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ai-learning-backend
  template:
    metadata:
      labels:
        app: ai-learning-backend
    spec:
      containers:
      - name: backend
        image: ai-learning-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-learning-secret
              key: GEMINI_API_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ai-learning-secret
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: ai-learning-config
              key: DATABASE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
