apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: ai-learning-backend
spec:
  type: ClusterIP
  selector:
    app: ai-learning-backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
