apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: ai-learning-frontend
spec:
  type: LoadBalancer
  selector:
    app: ai-learning-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
